development:
  adapter: mysql2
  database: luntan
  host: localhost
  username: root
  password: root
  encoding: utf8mb4

production:
  adapter: mysql2
  database: luntan
  host: localhost
  username: root
  password: root
  encoding: utf8mb4
